version: "3.8"

services:
  secure-chat-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - GIN_MODE=release
